# Generated by Django 5.2.8 on 2025-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
